/**
 * Appwrite Function: generate-export
 *
 * Trigger: HTTP from mobile app when user taps "Export case bundle".
 * Premium-only (caller MUST verify entitlement before calling; this function
 * also re-checks `entitlements.isPremium` for the requesting user).
 *
 * Responsibilities:
 *   1. Load a case + parties + events + issue flags + documents from Appwrite.
 *   2. Stream every raw-document file into a ZIP archive in memory.
 *   3. Add a generated `case-summary.md` and `timeline.csv` describing the case
 *      in attorney-friendly form (with all standard disclaimers).
 *   4. Upload the ZIP to the `generated-exports` bucket.
 *   5. Insert a row in `exports` with the resulting fileId and a 7-day expiry.
 *   6. Return a download URL (Appwrite getFileDownload).
 *
 * Env vars: same Appwrite vars as siblings, plus:
 *   APPWRITE_EXPORTS_BUCKET   (default: generated-exports)
 *   APPWRITE_RAW_BUCKET       (default: raw-documents)
 *
 * Request: { caseId, userId }
 */

const sdk = require('node-appwrite');
// node-appwrite >=14 moved InputFile out of the root export and into a
// dedicated entrypoint at 'node-appwrite/file'. v13 also exposes it there.
// Importing the new path keeps the function working across both versions.
const { InputFile } = require('node-appwrite/file');
const archiver = require('archiver');
const { PassThrough } = require('stream');

/** Parse a request body without ever throwing. Returns null on malformed input. */
function safeJsonParse(raw) {
  if (raw == null) return {};
  if (typeof raw === 'object') return raw;
  try {
    return JSON.parse(raw || '{}');
  } catch (_) {
    return null;
  }
}

/**
 * Best-effort HIPAA §164.312(b) audit write. Records who exported which case.
 * Never throws — a failed audit write must not abort the export, but it is
 * logged so the gap is visible.
 */
async function writeAudit(databases, dbId, entry, log) {
  try {
    await databases.createDocument(dbId, 'audit_log', sdk.ID.unique(), {
      actor: entry.actor,
      action: entry.action,
      resourceType: entry.resourceType,
      resourceId: entry.resourceId,
      outcome: entry.outcome,
      occurredAt: new Date().toISOString(),
    });
  } catch (e) {
    log(`[audit] write failed (action=${entry.action}): ${e.message}`);
  }
}

const DISCLAIMER = `
DISCLAIMER
==========
This bundle was generated by the Family Rights App for personal record-keeping
and attorney review. NOTHING IN THIS PACKAGE CONSTITUTES LEGAL ADVICE. Issue
flags are surfaced for review only and are not legal conclusions. Verify every
fact, date, and reference against the original court record before relying on
it in any proceeding.
`.trim();

module.exports = async ({ req, res, log, error }) => {
  try {
    const {
      APPWRITE_ENDPOINT,
      APPWRITE_PROJECT_ID,
      APPWRITE_API_KEY,
      APPWRITE_DATABASE_ID = 'family_rights_main',
      APPWRITE_EXPORTS_BUCKET = 'generated-exports',
      APPWRITE_RAW_BUCKET = 'raw-documents',
    } = process.env;

    if (!APPWRITE_ENDPOINT || !APPWRITE_PROJECT_ID || !APPWRITE_API_KEY) {
      throw new Error('Missing Appwrite environment configuration');
    }

    const body = safeJsonParse(req.bodyRaw ?? req.body);
    if (body === null) return res.json({ ok: false, error: 'Malformed JSON body' }, 400);
    const { caseId, userId } = body;
    if (!caseId || !userId) {
      return res.json({ ok: false, error: 'caseId and userId required' }, 400);
    }

    const client = new sdk.Client()
      .setEndpoint(APPWRITE_ENDPOINT)
      .setProject(APPWRITE_PROJECT_ID)
      .setKey(APPWRITE_API_KEY);
    const databases = new sdk.Databases(client);
    const storage = new sdk.Storage(client);

    // ----- Entitlement check -----
    // Entitlements are keyed by userId — see scripts/provision-appwrite.ts
    // (idx_user unique on userId) and the SubscriptionEntitlement contract in
    // src/domain/entities/index.ts.
    let entitlement;
    try {
      const ents = await databases.listDocuments(
        APPWRITE_DATABASE_ID,
        'entitlements',
        [sdk.Query.equal('userId', userId), sdk.Query.limit(1)],
      );
      entitlement = ents.documents[0];
    } catch (_) {
      return res.json({ ok: false, error: 'No active entitlement. Export is a premium feature.' }, 402);
    }
    // SubscriptionStatus 'trialing' (NOT 'trial') is the canonical value
    // emitted by mapState in verify-purchase and consumed by the mobile app.
    const isPremium =
      entitlement?.isPremium === true ||
      ['trialing', 'active', 'grace_period'].includes(entitlement?.status);
    if (!isPremium) {
      return res.json({ ok: false, error: 'Premium subscription required to export.' }, 402);
    }

    // ----- Load case data -----
    const caseRow = await databases.getDocument(APPWRITE_DATABASE_ID, 'cases', caseId);
    if (caseRow.ownerUserId !== userId) {
      await writeAudit(databases, APPWRITE_DATABASE_ID, {
        actor: userId, action: 'export.create', resourceType: 'case', resourceId: caseId, outcome: 'denied',
      }, log);
      return res.json({ ok: false, error: 'Forbidden' }, 403);
    }

    const [parties, events, flags, docs] = await Promise.all([
      listAll(databases, APPWRITE_DATABASE_ID, 'case_parties', [sdk.Query.equal('caseId', caseId)]),
      listAll(databases, APPWRITE_DATABASE_ID, 'case_events', [sdk.Query.equal('caseId', caseId), sdk.Query.orderAsc('occurredAt')]),
      listAll(databases, APPWRITE_DATABASE_ID, 'issue_flags', [sdk.Query.equal('caseId', caseId)]),
      listAll(databases, APPWRITE_DATABASE_ID, 'documents', [sdk.Query.equal('caseId', caseId)]),
    ]);

    // ----- Build markdown summary -----
    const md = buildMarkdownSummary(caseRow, parties, events, flags, docs);
    const csv = buildTimelineCsv(events);

    // ----- Stream ZIP -----
    const archive = archiver('zip', { zlib: { level: 9 } });
    const passthrough = new PassThrough();
    const chunks = [];
    passthrough.on('data', (c) => chunks.push(c));
    const done = new Promise((resolve, reject) => {
      passthrough.on('end', resolve);
      passthrough.on('error', reject);
      archive.on('error', reject);
    });
    archive.pipe(passthrough);

    archive.append(DISCLAIMER + '\n', { name: 'README.txt' });
    archive.append(md, { name: 'case-summary.md' });
    archive.append(csv, { name: 'timeline.csv' });

    for (const d of docs) {
      if (!d.fileId) continue;
      try {
        const buf = await storage.getFileDownload(APPWRITE_RAW_BUCKET, d.fileId);
        const data = Buffer.isBuffer(buf) ? buf : Buffer.from(buf);
        const safeName = (d.title || d.fileId).replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 80);
        archive.append(data, { name: `documents/${safeName}` });
      } catch (e) {
        log(`Skipping doc ${d.$id}: ${e.message}`);
      }
    }

    await archive.finalize();
    await done;

    const zipBuffer = Buffer.concat(chunks);

    // ----- Upload to storage -----
    const fileName = `case-${caseId}-${Date.now()}.zip`;
    // InputFile lives at 'node-appwrite/file' in v13+; the previous
    // `sdk.InputFile.fromBuffer(...)` resolved to undefined and threw at
    // runtime.
    const inputFile = InputFile.fromBuffer(zipBuffer, fileName);
    const uploaded = await storage.createFile(APPWRITE_EXPORTS_BUCKET, sdk.ID.unique(), inputFile, [
      sdk.Permission.read(sdk.Role.user(userId)),
      sdk.Permission.delete(sdk.Role.user(userId)),
    ]);

    // ----- Record export row -----
    const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
    const exportRow = await databases.createDocument(
      APPWRITE_DATABASE_ID,
      'exports',
      sdk.ID.unique(),
      {
        ownerId: userId,
        caseId,
        fileId: uploaded.$id,
        fileName,
        sizeBytes: zipBuffer.length,
        documentCount: docs.length,
        eventCount: events.length,
        flagCount: flags.length,
        expiresAt,
        createdAt: new Date().toISOString(),
      },
      [
        sdk.Permission.read(sdk.Role.user(userId)),
        sdk.Permission.delete(sdk.Role.user(userId)),
      ],
    );

    await writeAudit(databases, APPWRITE_DATABASE_ID, {
      actor: userId, action: 'export.create', resourceType: 'case', resourceId: caseId, outcome: 'success',
    }, log);

    const downloadUrl = `${APPWRITE_ENDPOINT}/storage/buckets/${APPWRITE_EXPORTS_BUCKET}/files/${uploaded.$id}/download?project=${APPWRITE_PROJECT_ID}`;

    return res.json({
      ok: true,
      exportId: exportRow.$id,
      fileId: uploaded.$id,
      fileName,
      sizeBytes: zipBuffer.length,
      expiresAt,
      downloadUrl,
    });
  } catch (e) {
    error(`generate-export failed: ${e.message}\n${e.stack}`);
    return res.json({ ok: false, error: 'Export generation failed. Please try again later.' }, 500);
  }
};

function buildMarkdownSummary(c, parties, events, flags, docs) {
  const lines = [];
  lines.push(`# Case Bundle: ${c.title || c.$id}`);
  lines.push('');
  lines.push(`> ${DISCLAIMER.replace(/\n/g, '\n> ')}`);
  lines.push('');
  lines.push('## Case');
  lines.push(`- **Title**: ${c.title}`);
  lines.push(`- **Court Case No.**: ${c.courtCaseNumber || 'n/a'}`);
  lines.push(`- **Lower Court Case No.**: ${c.lowerCourtCaseNumber || 'n/a'}`);
  lines.push(`- **Jurisdiction**: ${c.jurisdiction || 'n/a'}`);
  lines.push(`- **Stage**: ${c.stage || 'n/a'}`);
  lines.push(`- **Opened**: ${c.openedAt || 'n/a'}`);
  lines.push('');
  lines.push('## Parties');
  for (const p of parties) {
    lines.push(`- **${p.role}**: ${p.name}${p.notes ? ` — ${p.notes}` : ''}`);
  }
  lines.push('');
  lines.push('## Timeline');
  for (const e of events) {
    lines.push(`- **${e.occurredAt || ''}** — ${e.title}${e.description ? `\n  - ${e.description.replace(/\n/g, '\n  - ')}` : ''}`);
  }
  lines.push('');
  lines.push('## Issue Flags For Attorney Review');
  lines.push('');
  lines.push('_Flags are surfaced for review only. They are not legal conclusions._');
  lines.push('');
  for (const f of flags) {
    lines.push(`- **${f.code}** — ${f.summary || ''}`);
    if (f.detail) lines.push(`  - ${f.detail.replace(/\n/g, '\n  - ')}`);
  }
  lines.push('');
  lines.push('## Documents Included');
  for (const d of docs) {
    lines.push(`- ${d.title || d.$id} (${d.mimeType || 'unknown'}, ${d.sizeBytes || 0} bytes)`);
  }
  return lines.join('\n');
}

function buildTimelineCsv(events) {
  const header = 'occurred_at,title,description,tags\n';
  const rows = events.map((e) => {
    const esc = (s) => `"${String(s || '').replace(/"/g, '""')}"`;
    return [esc(e.occurredAt), esc(e.title), esc(e.description), esc((e.tags || []).join('|'))].join(',');
  });
  return header + rows.join('\n');
}

async function listAll(db, dbId, colId, baseQueries) {
  const all = [];
  let cursor;
  while (true) {
    const queries = [...baseQueries, sdk.Query.limit(100)];
    if (cursor) queries.push(sdk.Query.cursorAfter(cursor));
    const page = await db.listDocuments(dbId, colId, queries);
    all.push(...page.documents);
    if (page.documents.length < 100) break;
    cursor = page.documents[page.documents.length - 1].$id;
  }
  return all;
}
