// Bundled extracted-text sidecars for SD38180 seeded documents.
// Generated by scripts/build-sd38180-extracted-text.ts from
// assets/seed-case-sd38180/extracted-text/*.txt
//
// At runtime the seeder reads the relevant sidecar by document-title key
// and stores it as extractedText on the DocumentRecord so the prejudicial-
// language scanner can run without needing an OCR pass.
//
// Why bundle as JS strings instead of fs reads? Expo Web cannot read arbitrary
// files; bundling guarantees the text reaches every platform.

// eslint-disable-next-line @typescript-eslint/no-var-requires
const sidecars: Record<string, string> = require('./sd38180-extracted-text.generated.json');

export function getExtractedTextByKey(key: string): string | undefined {
  return sidecars[key];
}

export function listExtractedTextKeys(): string[] {
  return Object.keys(sidecars);
}
